Solution1
G0-G4/hh-school-2023-java-collections-stream pull request #3
Opened 2023-11-22 21:27 UTC by G0-G4

2023-11-22 21:32 UTC, G0-G4 commented on src/main/java/tasks/Task8.java
> +    return !Collections.disjoint(new HashSet<>(persons1), persons2);
теперь работает за O(n). Если убрать HashSet будет зависеть от переданных коллекций в худшем случае будет O(n^2)

2023-11-22 21:34 UTC, G0-G4 commented on src/main/java/tasks/Task8.java
> -    persons.remove(0);
Точно, в тот раз как-то пропустил, что это защита от remove. Плохо то, что меняются переданные в метод данные.

2023-11-26 11:30 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +    ArrayList<Person> sortedPersons = new ArrayList<>(persons);
а зачем ArrayList?

почему не сразу persons.stream().sorted().toList()?
тут как раз оверхеда особо то нет, ведь надо отсортировать и создать лист (что ты и делаешь) и стрим позволяет не объявлять переменную лишнюю

2023-11-26 11:34 UTC, genroelgvozo requested changes

2023-11-26 11:34 UTC, genroelgvozo commented on src/main/java/tasks/Task5.java
> +        .map(p -> personConverter.convert(p, personAreaIds.get(p.getId())))
байтики экономим)

2023-11-26 11:34 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +        .collect(Collectors.toSet());
все гуд (кроме экономии байтиков), единственное с точки зрения дальнейших правок кода - прикольно такой "формат" выносить в метод/конвертер, ведь это по факту какой-то фронт/апи формат. И тогда кажется метод сам захочет решать какие ему поля нужны из кандидата и арейки (ведь может не только быть название арейки, а какой-нибудь госномер). И тогда (что ты и так сделал) - мапа на арейки а не сразу на их имена приобретает смысл больший)

2023-11-26 11:34 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +      result += " " + person.getMiddleName();
скажу что здесь еще есть баг (с пробелами)
И вот если его фиксить то ифы еще более сложные (даже вложенные где-то будут)

В целом допустим такой код, но хочется лаконично видить "что нужно то в итоге" тремя строками, чем вникать в эти ифы все)

2023-11-28 08:13 UTC, G0-G4 commented on src/main/java/tasks/Task6.java
> +        .collect(Collectors.toSet());
Под форматом, который можно вынести в отдельный метод имелась в виду часть в map?
```
areaId -> person.getFirstName() + " - " + areasMap.get(areaId).getName())
```

2023-11-30 17:09 UTC, genroelgvozo approved these changes

2023-11-30 17:09 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +        .collect(Collectors.toSet());
да, но это на будущее коммент

2023-12-24 10:38 UTC, merged